using Pgvector;

namespace RPlus.Hunter.API.Persistence;

/// <summary>
/// Company knowledge base entry for RAG (Retrieval Augmented Generation).
/// Each row is a fact about the company that the AI recruiter can reference.
///
/// Vector embeddings are generated by nomic-embed-text (768 dimensions)
/// and stored via pgvector for cosine similarity search.
/// </summary>
public class CompanyKnowledge
{
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>Category: company, vacancy, benefits, process, etc.</summary>
    public required string Category { get; init; }

    /// <summary>Plain text content of the knowledge entry.</summary>
    public required string Content { get; init; }

    /// <summary>Vector embedding (768d, nomic-embed-text).</summary>
    public Vector? Embedding { get; set; }

    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;
}
