// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPlus.HR.Infrastructure.Persistence;

#nullable disable

namespace RPlus.HR.Infrastructure.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260124065343_HrV2")]
    partial class HrV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RPlus.HR.Domain.Entities.BankDetails", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("BankName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Iban")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("iban");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_hr_bank_details");

                    b.ToTable("hr_bank_details", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.EmployeeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("issued_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("number");

                    b.Property<Guid?>("ScanFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_file_id");

                    b.Property<string>("Series")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("series");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hr_documents");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_hr_documents_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hr_documents_user_id");

                    b.ToTable("hr_documents", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.EmployeeProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BloodType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blood_type");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("KZ")
                        .HasColumnName("citizenship");

                    b.Property<string>("ClothingSize")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("clothing_size");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisabilityGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("None")
                        .HasColumnName("disability_group");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Iin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("iin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("personal_email");

                    b.Property<string>("PersonalPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("personal_phone");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("place_of_birth");

                    b.Property<int?>("ShoeSize")
                        .HasColumnType("integer")
                        .HasColumnName("shoe_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_hr_profiles");

                    b.HasIndex("Iin")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_profiles_iin");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hr_profiles_status");

                    b.ToTable("hr_profiles", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDependent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dependent");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_hr_family_members");

                    b.HasIndex("Relation")
                        .HasDatabaseName("ix_hr_family_members_relation");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hr_family_members_user_id");

                    b.ToTable("hr_family_members", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.HrAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("ActorService")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_service");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_hr_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_hr_audit_logs_actor_user_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_hr_audit_logs_entity_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_hr_audit_logs_occurred_at");

                    b.ToTable("hr_audit_logs", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.MilitaryRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLiable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_liable");

                    b.Property<string>("LocalOffice")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("local_office");

                    b.Property<string>("Rank")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VusCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vus_code");

                    b.HasKey("UserId")
                        .HasName("pk_hr_military_records");

                    b.ToTable("hr_military_records", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.BankDetails", b =>
                {
                    b.HasOne("RPlus.HR.Domain.Entities.EmployeeProfile", null)
                        .WithOne("BankDetails")
                        .HasForeignKey("RPlus.HR.Domain.Entities.BankDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_bank_details_hr_profiles_user_id");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.EmployeeDocument", b =>
                {
                    b.HasOne("RPlus.HR.Domain.Entities.EmployeeProfile", null)
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_documents_hr_profiles_user_id");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.EmployeeProfile", b =>
                {
                    b.OwnsOne("RPlus.HR.Domain.Entities.EmployeeAddress", "RegistrationAddress", b1 =>
                        {
                            b1.Property<Guid>("EmployeeProfileUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Building")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("registration_address_building");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("registration_address_city");

                            b1.Property<string>("District")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("registration_address_district");

                            b1.Property<string>("Flat")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("registration_address_flat");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("registration_address_region");

                            b1.Property<string>("Street")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("registration_address_street");

                            b1.HasKey("EmployeeProfileUserId");

                            b1.ToTable("hr_profiles", "hr");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeProfileUserId")
                                .HasConstraintName("fk_hr_profiles_hr_profiles_user_id");
                        });

                    b.OwnsOne("RPlus.HR.Domain.Entities.EmployeeAddress", "ResidentialAddress", b1 =>
                        {
                            b1.Property<Guid>("EmployeeProfileUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Building")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("residential_address_building");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("residential_address_city");

                            b1.Property<string>("District")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("residential_address_district");

                            b1.Property<string>("Flat")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("residential_address_flat");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("residential_address_region");

                            b1.Property<string>("Street")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("residential_address_street");

                            b1.HasKey("EmployeeProfileUserId");

                            b1.ToTable("hr_profiles", "hr");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeProfileUserId")
                                .HasConstraintName("fk_hr_profiles_hr_profiles_user_id");
                        });

                    b.Navigation("RegistrationAddress");

                    b.Navigation("ResidentialAddress");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("RPlus.HR.Domain.Entities.EmployeeProfile", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_family_members_hr_profiles_user_id");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.MilitaryRecord", b =>
                {
                    b.HasOne("RPlus.HR.Domain.Entities.EmployeeProfile", null)
                        .WithOne("MilitaryRecord")
                        .HasForeignKey("RPlus.HR.Domain.Entities.MilitaryRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_military_records_hr_profiles_user_id");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.EmployeeProfile", b =>
                {
                    b.Navigation("BankDetails");

                    b.Navigation("Documents");

                    b.Navigation("FamilyMembers");

                    b.Navigation("MilitaryRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
