// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPlus.HR.Infrastructure.Persistence;

#nullable disable

namespace RPlus.HR.Infrastructure.Migrations
{
    [DbContext(typeof(HrDbContext))]
    partial class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BloodType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("blood_type");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("KZ")
                        .HasColumnName("citizenship");

                    b.Property<string>("ClothingSize")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("clothing_size");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDataJson")
                        .HasColumnType("text")
                        .HasColumnName("custom_data_json");

                    b.Property<string>("DisabilityGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("None")
                        .HasColumnName("disability_group");

                    b.Property<Guid?>("DocumentsFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("documents_folder_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<string>("Iin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("iin");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PersonalEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("personal_email");

                    b.Property<string>("PersonalPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("personal_phone");

                    b.Property<Guid?>("PhotoFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_file_id");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("place_of_birth");

                    b.Property<int?>("ShoeSize")
                        .HasColumnType("integer")
                        .HasColumnName("shoe_size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_hr_profiles");

                    b.HasIndex("Iin")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_profiles_iin");

                    b.HasIndex("PhotoFileId")
                        .HasDatabaseName("ix_hr_profiles_photo_file_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hr_profiles_status");

                    b.ToTable("hr_profiles", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.BankDetails", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("BankName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Iban")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("iban");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_hr_bank_details");

                    b.ToTable("hr_bank_details", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.HrAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("ActorService")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_service");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_hr_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_hr_audit_logs_actor_user_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_hr_audit_logs_entity_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_hr_audit_logs_occurred_at");

                    b.ToTable("hr_audit_logs", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.HrCustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("group");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_length");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Pattern")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pattern");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("placeholder");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hr_custom_fields");

                    b.HasIndex("Group")
                        .HasDatabaseName("ix_hr_custom_fields_group");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_hr_custom_fields_is_active");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("ix_hr_custom_fields_is_system");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_hr_custom_fields_key");

                    b.ToTable("hr_custom_fields", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.HrCustomFieldValue", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("FieldKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("UserId", "FieldKey")
                        .HasName("pk_hr_custom_values");

                    b.HasIndex("FieldKey")
                        .HasDatabaseName("ix_hr_custom_values_field_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_hr_custom_values_user_id");

                    b.ToTable("hr_custom_values", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.HrFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_hr_files");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_hr_files_owner_user_id");

                    b.ToTable("hr_files", "hr");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.MilitaryRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsLiable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_liable");

                    b.Property<string>("LocalOffice")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("local_office");

                    b.Property<string>("Rank")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VusCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vus_code");

                    b.HasKey("UserId")
                        .HasName("pk_hr_military_records");

                    b.ToTable("hr_military_records", "hr");
                });

            modelBuilder.Entity("EmployeeProfile", b =>
                {
                    b.OwnsOne("RPlus.HR.Domain.Entities.EmployeeAddress", "RegistrationAddress", b1 =>
                        {
                            b1.Property<Guid>("EmployeeProfileUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Building")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("registration_address_building");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("registration_address_city");

                            b1.Property<string>("District")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("registration_address_district");

                            b1.Property<string>("Flat")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("registration_address_flat");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("registration_address_region");

                            b1.Property<string>("Street")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("registration_address_street");

                            b1.HasKey("EmployeeProfileUserId");

                            b1.ToTable("hr_profiles", "hr");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeProfileUserId")
                                .HasConstraintName("fk_hr_profiles_hr_profiles_user_id");
                        });

                    b.OwnsOne("RPlus.HR.Domain.Entities.EmployeeAddress", "ResidentialAddress", b1 =>
                        {
                            b1.Property<Guid>("EmployeeProfileUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Building")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("residential_address_building");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("residential_address_city");

                            b1.Property<string>("District")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("residential_address_district");

                            b1.Property<string>("Flat")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("residential_address_flat");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("residential_address_region");

                            b1.Property<string>("Street")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("residential_address_street");

                            b1.HasKey("EmployeeProfileUserId");

                            b1.ToTable("hr_profiles", "hr");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeProfileUserId")
                                .HasConstraintName("fk_hr_profiles_hr_profiles_user_id");
                        });

                    b.OwnsMany("RPlus.HR.Domain.Entities.EmployeeDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("EmployeeProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateOnly?>("ExpiryDate")
                                .HasColumnType("date");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("IssueDate")
                                .HasColumnType("date");

                            b1.Property<string>("IssuedBy")
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid?>("ScanFileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Series")
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("EmployeeProfileUserId", "__synthesizedOrdinal");

                            b1.ToTable("hr_profiles", "hr");

                            b1.ToJson("documents");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeProfileUserId")
                                .HasConstraintName("fk_hr_profiles_hr_profiles_employee_profile_user_id");
                        });

                    b.OwnsMany("RPlus.HR.Domain.Entities.FamilyMember", "FamilyMembers", b1 =>
                        {
                            b1.Property<Guid>("EmployeeProfileUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateOnly?>("BirthDate")
                                .HasColumnType("date");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDependent")
                                .HasColumnType("boolean");

                            b1.Property<int>("Relation")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("EmployeeProfileUserId", "__synthesizedOrdinal");

                            b1.ToTable("hr_profiles", "hr");

                            b1.ToJson("family_members");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeProfileUserId")
                                .HasConstraintName("fk_hr_profiles_hr_profiles_employee_profile_user_id");

                            b1.OwnsMany("RPlus.HR.Domain.Entities.FamilyMemberDocument", "Documents", b2 =>
                                {
                                    b2.Property<Guid>("FamilyMemberEmployeeProfileUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("FamilyMember__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("FamilyMemberId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("FileId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("Size")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("UserId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("FamilyMemberEmployeeProfileUserId", "FamilyMember__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("hr_profiles", "hr");

                                    b2.ToJson("family_members");

                                    b2.WithOwner("FamilyMember")
                                        .HasForeignKey("FamilyMemberEmployeeProfileUserId", "FamilyMember__synthesizedOrdinal")
                                        .HasConstraintName("fk_hr_profiles_hr_profiles_family_member_employee_profile_user_id_f");

                                    b2.Navigation("FamilyMember");
                                });

                            b1.Navigation("Documents");
                        });

                    b.Navigation("Documents");

                    b.Navigation("FamilyMembers");

                    b.Navigation("RegistrationAddress");

                    b.Navigation("ResidentialAddress");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.BankDetails", b =>
                {
                    b.HasOne("EmployeeProfile", null)
                        .WithOne("BankDetails")
                        .HasForeignKey("RPlus.HR.Domain.Entities.BankDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_bank_details_hr_profiles_user_id");
                });

            modelBuilder.Entity("RPlus.HR.Domain.Entities.MilitaryRecord", b =>
                {
                    b.HasOne("EmployeeProfile", null)
                        .WithOne("MilitaryRecord")
                        .HasForeignKey("RPlus.HR.Domain.Entities.MilitaryRecord", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hr_military_records_hr_profiles_user_id");
                });

            modelBuilder.Entity("EmployeeProfile", b =>
                {
                    b.Navigation("BankDetails");

                    b.Navigation("MilitaryRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
