// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPlus.Organization.Infrastructure.Persistence;

#nullable disable

namespace RPlus.Organization.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    [Migration("20260124075343_DiagnosePendingModelChanges")]
    partial class DiagnosePendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organization")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.NodeContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InheritanceStrategy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("TenantId", "NodeId", "ResourceType", "ValidTo");

                    b.ToTable("node_contexts", "organization");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.OrgNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TenantId", "ParentId");

                    b.HasIndex("TenantId", "Path")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsDeleted", "ValidTo");

                    b.ToTable("org_nodes", "organization");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Attributes")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVacant")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportsToPositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ReportsToPositionId");

                    b.HasIndex("TenantId", "ReportsToPositionId");

                    b.HasIndex("TenantId", "NodeId", "IsDeleted");

                    b.ToTable("positions", "organization");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.PositionContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InheritanceStrategy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TenantId", "PositionId", "ResourceType", "ValidTo");

                    b.ToTable("position_contexts", "organization");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.UserAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("FtePercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacementForAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ReplacementForAssignmentId");

                    b.HasIndex("TenantId", "NodeId", "IsDeleted", "ValidTo");

                    b.HasIndex("TenantId", "PositionId", "IsDeleted", "ValidTo");

                    b.HasIndex("TenantId", "UserId", "IsDeleted", "ValidTo");

                    b.ToTable("user_assignments", "organization");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.UserRoleOverride", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssignmentId", "RoleCode");

                    b.ToTable("user_role_overrides", "organization");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.NodeContext", b =>
                {
                    b.HasOne("RPlus.Organization.Domain.Entities.OrgNode", "Node")
                        .WithMany("Contexts")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.OrgNode", b =>
                {
                    b.HasOne("RPlus.Organization.Domain.Entities.OrgNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.Position", b =>
                {
                    b.HasOne("RPlus.Organization.Domain.Entities.OrgNode", "Node")
                        .WithMany("Positions")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPlus.Organization.Domain.Entities.Position", "ReportsToPosition")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportsToPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Node");

                    b.Navigation("ReportsToPosition");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.PositionContext", b =>
                {
                    b.HasOne("RPlus.Organization.Domain.Entities.Position", "Position")
                        .WithMany("Contexts")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.UserAssignment", b =>
                {
                    b.HasOne("RPlus.Organization.Domain.Entities.OrgNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPlus.Organization.Domain.Entities.Position", "Position")
                        .WithMany("Assignments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPlus.Organization.Domain.Entities.UserAssignment", "ReplacementForAssignment")
                        .WithMany()
                        .HasForeignKey("ReplacementForAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Node");

                    b.Navigation("Position");

                    b.Navigation("ReplacementForAssignment");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.UserRoleOverride", b =>
                {
                    b.HasOne("RPlus.Organization.Domain.Entities.UserAssignment", "Assignment")
                        .WithMany("RoleOverrides")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.OrgNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Contexts");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.Position", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Contexts");

                    b.Navigation("DirectReports");
                });

            modelBuilder.Entity("RPlus.Organization.Domain.Entities.UserAssignment", b =>
                {
                    b.Navigation("RoleOverrides");
                });
#pragma warning restore 612, 618
        }
    }
}
